apiVersion: apps/v1
kind: Deployment
metadata:
  name: mainnet-poly-to-starcoin-relayer-deployment
  labels:
    app: mainnet-poly-to-starcoin-relayer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mainnet-poly-to-starcoin-relayer
  template:
    metadata:
      labels:
        app: mainnet-poly-to-starcoin-relayer
    spec:
      containers:
        - name: mainnet-poly-to-starcoin-relayer
          image: ghcr.io/elements-studio/poly_starcoin_relayer:sha-4d7f816
          ports:
            - containerPort: 8600
          env:
            - name: TO_POLY_DISABLED
              value: "true"
            - name: MYSQL_DSN_MAINNET
              valueFrom:
                secretKeyRef:
                  name: poly-starcoin-relayer-mainnet-sercets
                  key: MYSQL_DSN_MAINNET
            - name: PRIVATE_KEY_a7cdbbd
              valueFrom:
                secretKeyRef:
                  name: poly-starcoin-relayer-mainnet-sercets
                  key: PRIVATE_KEY_a7cdbbd
            - name: PRIVATE_KEY_da8671c
              valueFrom:
                secretKeyRef:
                  name: poly-starcoin-relayer-mainnet-sercets
                  key: PRIVATE_KEY_da8671c
            - name: POLY_WALLET_PASSWORD
              value: "123456"
            - name: POLY_WALLET_FILE
              value: "/etc/polynetwork/poly/wallet.dat"
            - name: ETHEREUM_CLIENT_URL_MAINNET
              valueFrom:
                secretKeyRef:
                  name: poly-starcoin-relayer-mainnet-sercets
                  key: ETHEREUM_CLIENT_URL
            - name: ALERT_DISCORD_WEBHOOK_URL
              valueFrom:
                secretKeyRef:
                  name: poly-starcoin-relayer-mainnet-sercets
                  key: ALERT_DISCORD_WEBHOOK_URL
            - name: GAS_SUBSIDY_TO_ADDRESS_BLACKLIST
              value: "2370df831df9220a9814f484893c97fe,a15a7fb5b0fde9b5277a1a5497535b12"
          volumeMounts:
            - name: poly-wallet-file
              mountPath: "/etc/polynetwork"
              readOnly: true

      volumes:
        - name: poly-wallet-file
          secret:
            secretName: poly-starcoin-relayer-mainnet-sercets
            items:
              - key: POLY_WALLET_JSON
                path: "poly/wallet.dat"
