#!/bin/bash
CURDIR=$(cd "$(dirname "$0")"; pwd)
docker run -d --name poly-starcoin-relayer -p 8081:8081  -e "STARCOIN_AIRDROP_MYSQL_HOST=${STARCOIN_AIRDROP_MYSQL_HOST}" -e "STARCOIN_AIRDROP_MYSQL_PORT=${STARCOIN_AIRDROP_MYSQL_PORT}" -e "STARCOIN_AIRDROP_MYSQL_USER=${STARCOIN_AIRDROP_MYSQL_USER}" -e "STARCOIN_AIRDROP_MYSQL_PWD=${STARCOIN_AIRDROP_MYSQL_PWD}" -e "STARCOIN_AIRDROP_MYSQL_DB=${STARCOIN_AIRDROP_MYSQL_DB}" poly-starcoin-relayer:latest

docker ps


